name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install platyPS
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name platyPS -Scope CurrentUser

    - name: Prepare Dependencies
      run: |
        LOCALPKG=`mktemp -d`
        wget -P "${LOCALPKG}" https://github.com/9506hqwy/xdr-net/releases/download/0.4.0/Xdr.0.4.0.nupkg
        wget -P "${LOCALPKG}" https://github.com/9506hqwy/libvirt-schema-net/releases/download/0.4.0/LibvirtModel.0.4.0.nupkg
        wget -P "${LOCALPKG}" https://github.com/9506hqwy/libvirt-remote-net/releases/download/0.2.0/LibvirtRemote.0.2.0.nupkg
        wget -P "${LOCALPKG}" https://github.com/9506hqwy/libvirt-header-net/releases/download/0.1.0/LibvirtHeader.0.1.0.nupkg
        dotnet nuget add source --name local "${LOCALPKG}"

    - name: Restore dependencies
      run: dotnet restore pwsh-virt.sln

    - name: Build
      run: dotnet build --no-restore pwsh-virt.sln

    - name: Check format
      run: dotnet format --no-restore --verify-no-changes pwsh-virt.sln

    - name: Publish
      run: dotnet publish --no-build pwsh-virt.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./artifacts pwsh-virt.sln

    - name: Generate coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"./artifacts/*/coverage.cobertura.xml" -targetdir:"./artifacts" -reporttypes:"MarkdownSummaryGithub;TextSummary"

    - name: Report coverage
      run: |
        cat "./artifacts/Summary.txt"
        cat "./artifacts/SummaryGithub.md" > $GITHUB_STEP_SUMMARY
